kind: pipeline
name: Build Container

steps:
- name: Build Container
  image: plugins/ecr
  settings:
    registry: 472510080448.dkr.ecr.us-east-1.amazonaws.com
    repo: sre-team/imagebuilder
    tags:
      - latest
      - 1.3
  when:
    branch:
    - main